# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Create a Release

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Read package
        id: package
        run: |
          content=`cat ./package.json | tr -d "\n"`
          echo "::set-output name=packageJson::$content"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          release_name: Release ${{fromJson(steps.package.outputs.packageJson).version}}
          tag_name: ${{fromJson(steps.package.outputs.packageJson).version}}
