# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI - Quality gates

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - development
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure NPM
        run: |
          npm config set @dipa-projekt:registry https://npm.pkg.github.com
          npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.NPMJS_GITHUB_PACKAGES_TOKEN }}
      - name: Install
        run: npm ci
      - name: Coverage
        run: npx lean coverage --check-coverage
      - name: Format
        run: npx lean format
      - name: Lint
        run: npx lean lint
      - name: Build
        run: npx lean build --gzip
